OLSR/olsrd

lib/pud/nmealib/include/nmealib/info.h
lib/pud/nmealib/src/info.c

This causes an error on older Ubuntu installations with cc ver. 4.6.3:
```
src/info.c: In function ‘nmeaTimeParseTime’:
src/info.c:95:49: error: declaration of ‘time’ shadows a global declaration [-Werror=shadow]
```

pud: fix of 'time' shadowing a global declaration

---

lib/nameservice/README_NAMESERVICE
lib/nameservice/src/nameservice.c

We add the 'sighup-interval' parameter to control the time interval
between sighups to the file specified by 'sighup-pid-file'.

nameservice: add new sighup-interval parameter

---

src/net_olsr.c

message was:
OLSR: sendto IPv4 Operation not permitted
message now:
OLSR: sendto IPv4 'Operation not permitted' on interface wlan1
(added also for the IPv6 case)

logging: show interface name during blocked socket error

---

lib/nameservice/README_NAMESERVICE
lib/nameservice/src/nameservice.c

playing around with the new option "sighup_interval" I found, that this also controls the interval of calling the "name-change-script".
Checking the code points out that this is the main-timer for writing any status-file to disk. So it's more consistent to change the parameter-name to what it's really doing.
Also update the README to reference this parameter in the others affected by it.
See #15

nameservice: rename parameter "sighup_interval" to "filewrite_interval"

---

lib/nameservice/Makefile

for the new parameter "filewrite-interval" we should bump the version, so init-scripts can give correct parameters.
Automatic generate config-files (like in OpenWrt from UCI-settings) have no knowledge if this parameter can be added to configfile when there is all the same version.
Signed-off-by: Sven Roederer <freifunk@it-solutions.geroedel.de>

nameservice: bump version to 0.4

---

src/bsd/net.c

Add a missing include for olsr_random() on BSD.

---

src/bsd/net.c

The media type of an interface can be used to tell wireless interfaces
apart. The SIOCGIFMEDIA ioctl works the same way across all BSDs,
whereas the net80211 ioctls used previously differ.

Implement a simpler way of detecting wifi interfaces on BSD.

---

src/bsd/kernel_routes.c

Specify a netmask when deleting routes. If no netmask is passed
in the routing message then deletion of the route can fail.
This fix covers both IPv4 and IPv6 routes.
Tested on OpenBSD only, but this change should not hurt other BSDs.

Fix route deletion on BSD.

---

src/gateway.c

If olsr_cnf->smart_gw_use_count is 1, no multi-gw tunnels are initialized, and
the sgwTunnel4InterfaceNames and sgwTunnel6InterfaceNames are actually NULL. Do
not attempt to cleanup those if NULL.
Symptom: stopping olsrd e.g. via SIGINT leads to a segfault during cleanup.
The reason is that smart_gw_use_count is 1, which attempts to then dereference
one of sgwTunnel{4,6}InterfaceNames[0], amounting to <NULL>[0].

fix: don't attempt to cleanup uninitialized multiGwTunnels

---

src/defs.h

When olsr_cnf is NULL, always print OLSR_PRINTF messages to avoid segfault.
I compiled olsrd and ran ./olsrd --help, resulting in a segfault.
That's because main.c prints an error message even before the config is loaded,
so that OLSR_PRINTF tries to lookup the logging level in a NULL olsr_cnf.

fix segfault when printing "You must be root"

---

src/bsd/kernel_routes.c

If a route to a given destination already exists, the add_del_route()
function attempts to delete this route before inserting a new one.
While doing so, it asks olsr_rt_flags() for route message flags to use.
It should ask for route message flags that apply to a deletion. However,
it only did so if the 'add' parameter is false. This looks like a case of
badly copy-pasted code, since this section of code is obviously trying
to delete a route regardless of the value of 'add'.

Use correct RTM flags while deleting a route on BSD.

---

src/bsd/kernel_routes.c

Same problem as fixed for IPv4 in 65978bd6996c8f62ac3f0adf971692fc8f2dc9cb.
I forgot to include the IPv6 code path in that commit.

Use correct RTM flags while deleting an IPv6 route on BSD.

---

src/bsd/net.c

OpenBSD no longer supports the net.inet6.icmp6.rediraccept sysctl.
It was removed in 2014: http://marc.info/?l=openbsd-cvs&m=140914827732101&w=2

Do not toggle net.inet6.icmp6.rediraccept on OpenBSD.

---

src/unix/ifnet.c

While reading an IPv4 broadcast address from the configuration file, do not
forget about initializing the length and family sockaddr_in struct fields.
Otherwise the sockaddr_in struct is invalid, and a BSD kernel will reject it.

Fix initialization of a struct sockaddr_in.

---

src/bsd/net.c

Sending multicast packets requires the IP_MULTICAST_IF socket option.
Without this socket option, packets sent to 255.255.255.255 are dropped.
With this change, olsr_sendto() can become a direct call to sendto() and
the -DSPOOF workaround which relies on libnet to send packets is no
longer required.
Tested on OpenBSD.

Fix olsr_sendto() for IPv4 on BSD.

---

src/mach/clock_gettime.c
src/mach/clock_gettime.h

Since Mac OSX 10.12 `clock_gettime()` is available and the compatibility function should no longer be build.

mach: clock_gettime and friends appeared in Mac OSX 10.12

---

src/routing_table.c

When rt_path is free'd from memory, references to it should be deleted.
Checking all rt_entry structs for rt_best pointers to the rt_path
that is to be deleted and nullify the pointer. Not doing so might
lead to segfaults.
Signed-off-by: Iwan G. Flameling <iwanovich@gmail.com>

routing: remove rt_entry.rt_best pointer when rt_path is deleted

---

README-Debian-package

Update the build instructions to use the maintained debian catalog.
This addresses issue #64 
Signed-off-by: pmelange <isprotejesvalkata@gmail.com>

README-Debian-package: Update build instructions

---

lib/pud/Makefile

nmealib is needed to build olsrd_pud plugin otherwise build fails on:
[LD] olsrd_pud.so.3.0.0 (nmealib dynamically linked)
/home/fabrice/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/arm-none-linux-gnueabi/4.8.3/../../../../arm-none-linux-gnueabi/bin/ld: cannot find -lnmea
wireformat/lib/libOlsrdPudWireFormat.so: file not recognized: File truncated
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

lib/pud/Makefile: fix parallel build

---

lib/pud/src/gpsdclient.c

The timestamp fields were changed from `double` to `struct timespec`, and
the geoid `separation` field was moved to `fix.geoid_sep`.
Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>
This is a quick patch to let it compile.  I can't run-test this, I've just compile-tested in using openwrt master, with gpsd 3.20 and 3.19, for a mvebu/arm_cortex-a9 target.

pud: adapt to API changes in gpsd 3.20

---

src/cfgparser/local.mk

With the upgrade to bison 3.7.1 (openwrt commit 1cf842d) building
olsrd was failing.  Now, instead of the contents of header files
being directly inserted into the generated source files, they are
instead included with a #include directive.
The local.mk has, until now, done some magic with *-tmp files,
which is not longer necessary and even causes builds to fail.
```
src/cfgparser/oparse.c:265:10: fatal error: oparse.h-tmp: No such file or directory
#include "oparse.h-tmp"
```
Suggested-by: Jo-Philipp Wich <jo@mein.io>
Signed-off-by: Perry Melange <isprotejesvalkata@gmail.com>
[Retrieved from:
https://github.com/openwrt-routing/packages/commit/5cc8e058850acbc22fe92c5e2b24863efc577971]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

olsrd: migrate to using bison 3.7.1

---

src/cli.c
src/process_package.c
src/routing_table.c

Two fixes encountered when running `olsrd -d 2 -ipv6 -i "uplink" -f /dev/null`, where the interface has no IPv4 address.

olsrd: various bugfixes

---

lib/bmf/src/Bmf.c

Musl library generates an error when including <sys/poll.h>.
POSIX specifications state that <poll.h> should be used.
Fixes warnings in the form of:
```
[CC] src/Bmf.c
In file included from src/Bmf.c:70:
/home/nick/openwrt/staging_dir/toolchain-mips_24kc_gcc-8.4.0_musl
/include/sys/poll.h:1:2: warning: #warning redirecting incorrect
#include <sys/poll.h> to <poll.h> [-Wcpp]
#warning redirecting incorrect #include <sys/poll.h> to <poll.h>
```

bmf: change include from sys/poll.h to poll.h

---

lib/pud/nmealib/Makefile.inc

When compiling pud with glibc it will result in
```
error: #warning _FORTIFY_SOURCE requires compiling with optimization
(-O) [-Werror=cpp]
^~~~~~~
cc1: all warnings being treated as errors
```
To compile pud with glibc again we remove Werror.

pud: fix openwrt glibc compilation

---

src/bsd/kernel_routes.c

Get the current routing table number from getrtable(2). This allows
running olsrd on an alternative routing table via 'route exec -T',
or by the setting 'olsrd_rtable' parameter to the desired routing
table number in /etc/rc.conf.local.

allow use of an alternative routing table on OpenBSD

---

Makefile
lib/filtergw/Makefile
lib/filtergw/src/olsrd_filtergw.c
lib/filtergw/src/olsrd_filtergw.h
lib/filtergw/src/olsrd_plugin.c
lib/filtergw/version-script.txt

The plugin adds a possibility to filter out gateway HNAs. This can be
very handy e.g. for faulty nodes. A gateway can be taken out directly on
a central node and all traffic is then redirected. Also the underlying
smart gateways are adapted. Currently the link multiplier is often used
to control a faulty node, but it is not necessarily the best way to do
so.
The plugin also allows to determine the smart gateway on the local node.
This way you can easily select another gateway node to direct traffic,
or block a specific one.
Here are some sample configurations:
Only allow Gateway HNA from '10.230.132.40':
config LoadPlugin
option library 'olsrd_filtergw'
list originator '10.230.132.40'
option allowlist '1'
Block Gateway HNA from '10.230.132.40':
config LoadPlugin
option library …

filtergw: add plugin allow to allow/block gateways (even smartgateway)

---

lib/pud/src/gpsdclient.c

This reverts commit 69ae23be9f96b9e7dd68a0252f3ad05986bb222d. Indeed, here is an extract of https://gpsd.gitlab.io/gpsd/gpsd_json.html:
> 
> The optional "status" field (aka fix type), is a modifier (adjective) to
> mode. It is not a replacement for, or superset of, the "mode" field. It
> is almost, but not quite, the same as the NMEA 4.x xxGGA GPS Quality
> Indicator Values. Many GNSS receivers do not supply it. Those that do
> interpret the specification in various incompatible ways.
So from my understanding, status field is optional and `STATUS_NO_FIX` has
been explicitly renamed into `STATUS_UNK` to avoid confusion with
`MODE_NO_FIX` (which is already handled by `gpsdclient.c`). I would advise
to drop the `if` block to really fix the build failure.
Signed-off-by: Fabrice Fontaine …

Revert "pud: fix build with gpsd >= 3.23.1"

---

lib/pud/src/gpsdclient.c

Here is an extract of https://gpsd.gitlab.io/gpsd/gpsd_json.html:
> The optional "status" field (aka fix type), is a modifier (adjective) to
> mode. It is not a replacement for, or superset of, the "mode" field. It
> is almost, but not quite, the same as the NMEA 4.x xxGGA GPS Quality
> Indicator Values. Many GNSS receivers do not supply it. Those that do
> interpret the specification in various incompatible ways.
So status field is optional and `STATUS_NO_FIX` has been explicitly
renamed into `STATUS_UNK` to avoid confusion with `MODE_NO_FIX` (which is
already handled by `gpsdclient.c`) so drop the `if` block to fix the build
failure with gpsd >= 3.23.1.
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

lib/pud/src/gpsdclient.c: drop handling of gpsdata->fix.status

---

src/unix/ifnet.c

Wireguard interfaces have no BROADCAST flag. We can also mesh on
point-to-point links. That is why we mesh now also on interfaces with
the IFF_POINTOPOINT flag enabled.
Signed-off-by: Nick Hainke <vincent@systemli.org>

unix: fix meshing with wireguard/point-to-point interfaces

---

lib/pud/src/gpsdclient.h

Fix build against gpsd-3.25.
Fixes: #118
Supersedes: #119
This was tested to fix the build with gpsd-3.25, as detected by Buildroot autobuilders:
http://autobuild.buildroot.org/results/47a619686bb47debd525c92aa7e14bee5c40ca9e

lib/pud: fix build with gpsd >= 3.25

---

lib/filtergw/src/olsrd_filtergw.c
src/linux/kernel_routes_nl.c

the msghdr has padding in both glibc and musl. Initialize with names to avoid dealing with the padding.
There's also a wrong struct type that's an error now.

fix compilation with GCC14

---

Makefile.inc
lib/pud/Makefile
lib/pud/src/gpsdclient.h

Introduce back the fixsource_t struct definition based on libgps version, retrieved from pkg-config.
This fixes the build with libgps versions inferior or equal to 3.24
Closes: https://github.com/OLSR/olsrd/pull/122 from which it is based off.

Fix build with libgps <= 3.24 using pkg-config
